### ISSUE TITLE
Throws exception on Windows 10, Python3.8.1 and Office 365 Powerpoint

### ISSUE THREAD

**Issue by SindreSB** [matthewrenze/powerpoint-to-pdf#1]
Hi,

The scripts aren't working for me, and I figured I'd ask here if you've seen this before. 

Steps:
Install Python 
pip install comtypes
python Convert.py file.pptx slides.pdf

This crashes with the following traceback:
```
Traceback (most recent call last):
  File ".\Convert.py", line 29, in <module>
    powerpoint = comtypes.client.CreateObject("Powerpoint.Application")
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\client\__init__.py", line 250, in CreateObject
    return _manage(obj, clsid, interface=interface)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\client\__init__.py", line 188, in _manage
    obj = GetBestInterface(obj)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\client\__init__.py", line 112, in GetBestInterface
    interface = getattr(mod, itf_name)
AttributeError: module 'comtypes.gen.PowerPoint' has no attribute '_Application'
```

Another, much more complex presentation failed with:

```
Traceback (most recent call last):
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'comtypes.automation.tagVARIANT'>,), 0)

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File ".\Convert.py", line 29, in <module>
    powerpoint = comtypes.client.CreateObject("Powerpoint.Application")
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\client\__init__.py", line 250, in CreateObject
    return _manage(obj, clsid, interface=interface)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\client\__init__.py", line 188, in _manage
    obj = GetBestInterface(obj)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\client\__init__.py", line 110, in GetBestInterface
    mod = GetModule(tlib)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\client\_generate.py", line 172, in _CreateWrapper
    generate_module(tlib, ofi, pathname)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\tools\tlbparser.py", line 750, in generate_module
    gen.generate_code(list(items.values()), filename=pathname)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\tools\codegenerator.py", line 241, in generate_code
    self.generate_all(items)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\tools\codegenerator.py", line 189, in generate_all
    self.generate(item)
e 185, in generate
    mth(item)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\tools\codegenerator.py", line 629, in External
    comtypes.client.GetModule(ext.tlib)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\gen\_2DF8D04C_5BFA_101B_BDE5_00AA0044DE52_0_2_8.py", line 68, in <module>
    EffectParameter._methods_ = [
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "C:\Users\sindr\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 125, in WINFUNCTYPE          class WinFunctionType(_CFuncPtr):
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.
```

**Comment by SindreSB** [comment]
Switching to win32com instead "worked on my machine". Since I'm guessing this is only a private utility, we'll not have a large discussion on it, but figured I'd leave a note about it. :) 

Anyway thanks for sharing this!

**Comment by matthewrenze** [comment]
@SindreSB Thanks for sharing the issue and your solution for others. 

I really appreciate it! : )
